setwd("C:/Users/caozhiy/Documents/data/ds4/project1")
dataFile <- "household_power_consumption.txt"
data <- read.table(dataFile, header=TRUE, sep=";", dec=".", skip=66637, nrows=2934)
names(data) <- c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3")
period <- strptime(paste(data$Date, data$Time, sep=" "), "%d/%m/%Y %H:%M:%S")
globalActivePower <- as.numeric(data$Global_active_power)
subMetering1 <- as.numeric(data$Sub_metering_1)
subMetering2 <- as.numeric(data$Sub_metering_2)
subMetering3 <- as.numeric(data$Sub_metering_3)
png("plot4.png", width=480, height=480)
par(mfcol = c(2,2))
plot(period, globalActivePower, type="l", xlab="", ylab="Global Active Power", cex=0.2)
plot(period, subMetering1, type="l", ylab="Energy Submetering", xlab="", col="black")
lines(period, subMetering2, type="l", col="red")
lines(period, subMetering3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2.5, col=c("black", "red", "blue"))
voltage <- as.numeric(data$Voltage)
plot(period, voltage, type="l", ylab="Voltage", xlab="datetime")
globalReactivePower <- as.numeric(data$Global_reactive_power)
plot(period, globalReactivePower, type="l", xlab="datetime", ylab="Global_reactive_power")
dev.off()
